//! Typed keys: one nameable Rust type per field of a section.
//!
//! Subscribing used to mean handing over a section string and a closure that
//! digs a field out of the parsed struct. Both halves were unchecked — the
//! string could be anything, and nothing tied the closure to the section it
//! was meant to read. A [`Key`] replaces the pair: it *is* the field, so the
//! section name, the field name and the field's type all travel together and
//! the compiler picks them up.
//!
//! ```ignore
//! use crownos_config::schema::appearance::BarHeight;
//!
//! // `bar_height` is a u32 because `BarHeight` says so.
//! let sub = crownos_config::subscribe_key(BarHeight, |bar_height| {
//!     resize_bar(bar_height);
//! });
//! ```
//!
//! Keys are generated by [`section!`](crate::section), which every schema
//! module uses to declare its struct, so a new field cannot exist without its
//! key and a renamed field breaks its subscribers at compile time rather than
//! silently going quiet.
//!
//! # Two flavours of key
//!
//! [`section!`] emits both a unit struct per field (the [`Key`] impls above,
//! typed and zero-sized) and one plain enum listing every field, e.g.
//! `AppearanceKey`. Use the unit structs to subscribe; use the enum when you
//! need to *talk about* keys at runtime — iterate them, log them, store them in
//! a set. [`Key::KEY`] converts a typed key into its enum variant.

use serde::de::DeserializeOwned;

/// One field of one settings section, as a type.
///
/// Implemented by the unit structs that [`section!`](crate::section) generates;
/// there is no reason to implement it by hand. Being `Copy` and zero-sized, a
/// key is free to pass around — every call site writes the type's name and gets
/// the field's real type back.
pub trait Key: Copy + Send + Sync + 'static {
    /// The settings struct this field belongs to.
    type Section: DeserializeOwned + Send + 'static;

    /// The type stored at this field.
    ///
    /// `Clone` because reading a key copies the value out of the parsed
    /// section, `PartialEq` because that is how "did this key change?" is
    /// answered.
    type Value: Clone + PartialEq + Send + 'static;

    /// The enum listing every key of [`Self::Section`].
    type Keys: Copy + PartialEq + 'static;

    /// File-name stem of the section, e.g. `"appearance"`.
    const SECTION: &'static str;

    /// The field's name as it appears in the RON file, e.g. `"bar_height"`.
    const NAME: &'static str;

    /// This key as a variant of [`Self::Keys`], for runtime use.
    const KEY: Self::Keys;

    /// Read this field out of a parsed section.
    fn get(section: &Self::Section) -> Self::Value;
}

/// Declare a settings section: the struct, its [`Default`], its section name,
/// and a [`Key`] for every field.
///
/// ```ignore
/// crate::section! {
///     /// The look of the desktop.
///     pub struct Appearance in "appearance", keys AppearanceKey {
///         /// Prefer light-on-dark.
///         pub dark_mode as DarkMode: bool = true,
///         pub bar_height as BarHeight: u32 = 32,
///     }
/// }
/// ```
///
/// expands to the struct (deriving `Debug, Clone, PartialEq, Serialize,
/// Deserialize`), `Appearance::SECTION`, a `Default` built from the `= value`
/// on each field, the unit key types `DarkMode` and `BarHeight`, and the enum
/// `AppearanceKey { DarkMode, BarHeight }`.
///
/// Doc comments and attributes are passed through to the struct and its fields,
/// so `#[serde(default)]` and friends work as usual.
///
/// # Why each field names its key
///
/// `dark_mode as DarkMode` says the same thing twice, which is annoying but
/// unavoidable: `macro_rules!` cannot build the identifier `DarkMode` out of
/// the identifier `dark_mode` — there is no stable way to concatenate or
/// re-case identifiers without a proc macro. The upside of writing it out is
/// that the key type is a normal, greppable, go-to-definition-able name.
#[macro_export]
macro_rules! section {
    (
        $(#[$section_meta:meta])*
        $vis:vis struct $Section:ident in $file:literal, keys $Keys:ident {
            $(
                $(#[$field_meta:meta])*
                $field_vis:vis $field:ident as $Key:ident : $ty:ty = $default:expr
            ),* $(,)?
        }
    ) => {
        $(#[$section_meta])*
        #[derive(::core::fmt::Debug, ::core::clone::Clone, ::core::cmp::PartialEq)]
        #[derive(::serde::Serialize, ::serde::Deserialize)]
        $vis struct $Section {
            $(
                $(#[$field_meta])*
                $field_vis $field: $ty,
            )*
        }

        impl $Section {
            #[doc = concat!("File-name stem of this section: `", $file, ".ron`.")]
            pub const SECTION: &'static str = $file;
        }

        #[allow(
            clippy::derivable_impls,
            reason = "generated from the `= value` on each field, not from the field's own Default"
        )]
        impl ::core::default::Default for $Section {
            fn default() -> Self {
                Self { $($field: $default,)* }
            }
        }

        #[doc = concat!("Every key of [`", stringify!($Section), "`], as a runtime value.")]
        ///
        /// Generated by [`section!`](crate::section). Subscribing uses the unit
        /// key types instead; this is for iterating, logging and bookkeeping.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        $vis enum $Keys {
            $(
                #[doc = concat!("The `", stringify!($field), "` field.")]
                $Key,
            )*
        }

        impl $Keys {
            /// Every key of this section, in declaration order.
            pub const ALL: &'static [Self] = &[$(Self::$Key,)*];

            #[doc = concat!("File-name stem of this section: `", $file, ".ron`.")]
            pub const SECTION: &'static str = $file;

            /// The field name as it appears in the RON file.
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$Key => stringify!($field),)*
                }
            }
        }

        impl ::core::fmt::Display for $Keys {
            /// Qualified as `<section>.<field>`, e.g. `appearance.bar_height`.
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                write!(f, "{}.{}", $file, self.as_str())
            }
        }

        $(
            #[doc = concat!(
                "The `", stringify!($field), "` key of [`", stringify!($Section),
                "`] (a [`", stringify!($ty), "`])."
            )]
            #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
            $vis struct $Key;

            impl $crate::Key for $Key {
                type Section = $Section;
                type Value = $ty;
                type Keys = $Keys;

                const SECTION: &'static str = $file;
                const NAME: &'static str = stringify!($field);
                const KEY: $Keys = $Keys::$Key;

                fn get(section: &$Section) -> $ty {
                    section.$field.clone()
                }
            }
        )*
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::{appearance, Appearance, AppearanceKey};

    /// The `= value` on each field is what `Default` uses.
    #[test]
    fn defaults_come_from_the_declaration() {
        let appearance = Appearance::default();

        assert!(appearance.dark_mode);
        assert_eq!(appearance.bar_height, 32);
        assert_eq!(appearance.transparency, 0.0);
        assert_eq!(appearance.wallpaper, "");
    }

    /// A typed key reads its own field, and nothing else.
    #[test]
    fn keys_read_their_field() {
        let appearance = Appearance {
            dark_mode: false,
            bar_height: 48,
            ..Appearance::default()
        };

        assert_eq!(appearance::BarHeight::get(&appearance), 48);
        assert!(!appearance::DarkMode::get(&appearance));
    }

    /// A key knows where it lives, in both forms.
    #[test]
    fn keys_carry_their_names() {
        assert_eq!(appearance::BarHeight::SECTION, Appearance::SECTION);
        assert_eq!(appearance::BarHeight::NAME, "bar_height");
        assert_eq!(appearance::BarHeight::KEY, AppearanceKey::BarHeight);
    }

    /// The dynamic enum covers every field, in declaration order, and prints
    /// qualified.
    #[test]
    fn the_key_enum_lists_every_field() {
        assert_eq!(
            AppearanceKey::ALL
                .iter()
                .map(|key| key.as_str())
                .collect::<Vec<_>>(),
            ["dark_mode", "accent", "transparency", "wallpaper", "bar_height"]
        );
        assert_eq!(
            AppearanceKey::BarHeight.to_string(),
            "appearance.bar_height"
        );
    }
}
